name: NodeJS CI

on: 
  push:
    branches:
      master
  pull_request:
    branches:
      master
  
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12.21.0']
        java: ['1.8']
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        with:
          java-version: ${{ matrix.java }}
        uses: actions/setup-java@v1
      - name: Set up NPM
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: mvn package (also runs npm test && npm build)
        run: mvn package -DskipITs
