name: NPM Publish

on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: NPM
        run: |
          cd javascript/src/typescript && npm install
          cd javascript/src/typescript && npm run build
          cd javascript/src/typescript && NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN} npm publish
