name: Publish Maven and NPM Artifacts

on: 
  push:
    branches:
      master
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: 12.21.0
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Update version
      run: |
        pip install --user yq
        export PATH="/home/runner/.local/bin:$PATH"
        ./update-versions.sh
    - name: Make release commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "CI: Update release versions" -a
    - name: Maven install
      run: |
        mkdir -p ~/.m2
        mvn --settings settings.xml clean install -Dmaven.wagon.http.pool=false -DskipITs
    - name: Maven Deploy
      run: |
        mkdir -p ~/.m2
        mvn --settings settings.xml clean deploy -Dmaven.wagon.http.pool=false -DskipITs
      env: 
        GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: x-access-token
    - name: NPM - Set auth token
      run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> ./javascript/src/typescript/.npmrc
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: NPM Publish
      working-directory: ./javascript/src/typescript
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        # npm uses the NODE_AUTH_TOKEN environment variable
      run: npm run publish:next
    - name: Make release commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "CI: Update javascript telemetry client version" -a
    - name: Push release commits
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'master'
